//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BRL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Cuenta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Cuenta()
        {
            this.tbl_Transaccion = new HashSet<tbl_Transaccion>();
        }
    
        public int idCuenta { get; set; }
        public string nombre { get; set; }
        public System.DateTime fechaCreacion { get; set; }
        public int idUsuario { get; set; }
        public bool eliminado { get; set; }
    
        public virtual tbl_Usuario tbl_Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Transaccion> tbl_Transaccion { get; set; }
    }
}
